jenkins2:  
  container_name: jenkins
  image: jenkins/jenkins:lts
  environment:  
    JAVA_OPTS: "-Djava.awt.headless=true"  
    JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Start jenkins unlocked  
  ports:  
    - "50000:50000"  
    - "8080:8080"  
  volumes:  
    - /var/jenkins_home